sudo: required
services:
  - docker

before_install:
  - docker build -t dnp1204/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run dnp1204/react-test npm run test -- --coverage

after_success:
  - docker build -t dnp1204/multi-client ./client
  - docker build -t dnp1204/multi-nginx ./nginx
  - docker build -t dnp1204/multi-server ./server
  - docker build -t dnp1204/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dnp1204/multi-client
  - docker push dnp1204/multi-nginx
  - docker push dnp1204/multi-server
  - docker push dnp1204/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-868660723002
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

notifications:
  email: false
